### ISSUE TITLE
SDP klienten har med seg genererte klasser fra Oppslagstjenesten som skaper konflikt med de klasser som selv generer for integrasjon mot Oppslagstjenesten

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-java-klient#23]
sdp-xsd har med seg oppslagstjenesten-metadata-14.05.xsd og generer klassene no.difi.begrep.Difi*** som kræsjer med de klassene jeg selv generer fra oppslagstjeneste wsdl'n.

## bakgrunn

- jeg har en enkel applikasjon som gjør oppslag mot oppslagstjenesten for så å sende ut digital post.
- applikasjonen generer integrasjonskode mot oppslagstjenesten ved å generer kildekode fra: http://begrep.difi.no/Oppslagstjenesten/3.0.2/xsd/oppslagstjeneste-ws-14-05.wsdl

Jeg får følgende runtime exception:

```
Two classes have the same XML type name "{http://begrep.difi.no}reservasjon". Use @XmlType.name and @XMLType.namespace to assign different names to them.
   this problem is related to the following location:
      at  no.difi.begrep.Reservasjon
      ........
  this problem is related to the following location:
      at  no.difi.begrep.DifiReservasjon
     .....
```

Det er samme feil for alle klassene som genereres ut i fra  oppslagstjenesten-metadata-14.05.xsd

**Comment by aberner** [comment]
org.apache.cxf.service.factory.ServiceConstructionException
                at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:327)
                at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)
                at .........

Caused by: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 7 counts of IllegalAnnotationExceptions
Two classes have the same XML type name "{http://begrep.difi.no}reservasjon". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.Reservasjon
                               at protected no.difi.begrep.Reservasjon no.difi.begrep.Person.reservasjon
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiReservasjon
                               at protected no.difi.begrep.DifiReservasjon no.difi.begrep.DifiPerson.reservasjon
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}status". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.Status
                               at protected no.difi.begrep.Status no.difi.begrep.Person.status
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiStatus
                               at protected no.difi.begrep.DifiStatus no.difi.begrep.DifiPerson.status
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Mobiltelefonnummer". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.Mobiltelefonnummer
                               at protected no.difi.begrep.Mobiltelefonnummer no.difi.begrep.Kontaktinformasjon.mobiltelefonnummer
                               at no.difi.begrep.Kontaktinformasjon
                               at protected no.difi.begrep.Kontaktinformasjon no.difi.begrep.Person.kontaktinformasjon
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiMobiltelefonnummer
                               at protected no.difi.begrep.DifiMobiltelefonnummer no.difi.begrep.DifiKontaktinformasjon.mobiltelefonnummer
                               at no.difi.begrep.DifiKontaktinformasjon
                               at protected no.difi.begrep.DifiKontaktinformasjon no.difi.begrep.DifiPerson.kontaktinformasjon
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Epostadresse". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.Epostadresse
                               at protected no.difi.begrep.Epostadresse no.difi.begrep.Kontaktinformasjon.epostadresse
                               at no.difi.begrep.Kontaktinformasjon
                               at protected no.difi.begrep.Kontaktinformasjon no.difi.begrep.Person.kontaktinformasjon
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiEpostadresse
                               at protected no.difi.begrep.DifiEpostadresse no.difi.begrep.DifiKontaktinformasjon.epostadresse
                               at no.difi.begrep.DifiKontaktinformasjon
                               at protected no.difi.begrep.DifiKontaktinformasjon no.difi.begrep.DifiPerson.kontaktinformasjon
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Kontaktinformasjon". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.Kontaktinformasjon
                               at protected no.difi.begrep.Kontaktinformasjon no.difi.begrep.Person.kontaktinformasjon
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiKontaktinformasjon
                               at protected no.difi.begrep.DifiKontaktinformasjon no.difi.begrep.DifiPerson.kontaktinformasjon
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}SikkerDigitalPostAdresse". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.SikkerDigitalPostAdresse
                               at protected no.difi.begrep.SikkerDigitalPostAdresse no.difi.begrep.Person.sikkerDigitalPostAdresse
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiSikkerDigitalPostAdresse
                               at protected no.difi.begrep.DifiSikkerDigitalPostAdresse no.difi.begrep.DifiPerson.sikkerDigitalPostAdresse
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory
Two classes have the same XML type name "{http://begrep.difi.no}Person". Use @XmlType.name and @XmlType.namespace to assign different names to them.
                this problem is related to the following location:
                               at no.difi.begrep.Person
                               at protected java.util.List no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons.person
                               at no.difi.kontaktinfo.xsd.oppslagstjeneste._14_05.HentEndringerRespons
                this problem is related to the following location:
                               at no.difi.begrep.DifiPerson
                               at public no.difi.begrep.DifiPerson no.difi.begrep.ObjectFactory.createDifiPerson()
                               at no.difi.begrep.ObjectFactory

                at com.sun.xml.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:106)
                at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:468)
                at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:300)
                at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
                at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1158)
                at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:483)
                at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
                at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
                at javax.xml.bind.ContextFinder.find(ContextFinder.java:441)
                at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
                at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:347)
                at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:345)
                at java.security.AccessController.doPrivileged(Native Method)
                at org.apache.cxf.common.jaxb.JAXBContextCache.createContext(JAXBContextCache.java:345)
                at org.apache.cxf.common.jaxb.JAXBContextCache.getCachedContextAndSchemas(JAXBContextCache.java:246)
                at org.apache.cxf.jaxb.JAXBDataBinding.createJAXBContextAndSchemas(JAXBDataBinding.java:470)
                at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:325)
                ... 59 more

**Comment by aberner** [comment]
Feilen har blitt løst ved å endre følgende fil:
https://github.com/digipost/sdp-shared/blob/master/xsd/src/main/jaxb/bindings.xjb

 jag har bara kommenterat ut føljande:
```

<!--<bindings schemaLocation="../difi-begrepskatalog/xsd/oppslag/oppslagstjeneste-metadata-14-05.xsd" node="/xs:schema">
   <schemaBindings>
      <nameXmlTransform>
         <typeName prefix="Difi" />
         <anonymousTypeName prefix="Difi" />
         <elementName prefix="Difi" />
      </nameXmlTransform>
   </schemaBindings>
</bindings>-->
```

**Comment by landro** [comment]
Oppdaterte avhengighet til sdp-shared i 238304ce87337cf0aa34137bc02b8263c8c65afe
