### ISSUE TITLE
Class cast exception

### ISSUE THREAD

**Issue by bedzon** [difi/sikker-digital-post-java-klient#26]
Kreftregisteret har ikke varit oppsatt som gyldig avsendere tidligere og derfor har vi en del brev som ikke blitt sendt riktig i testmiljöet. Når vi pröver at hente en leveringskvittering for disse brevene får vi nå en class cast exception:

I de fall vi får en feil-kvittering fra dere av typen «no.difi.begrep.sdp.schema_v10.SDPFeil» så får vi en feil når det skal type casta denne meldingen til en «no.difi.begrep.sdp.schema_v10.SDPKvittering». Skal det ikke vare mulig å gjöre det på den måten? Jeg tror dette sker inne i deres kode.
Så her ser koden ut som pröver å hente kvittering:

try {
    lastReceipt = getLetterReceiptAndAcknowledgeLastOne(lastReceipt);
    if(!isSendingQueueEmpty()) {
        SdpLetterPackage workingPackage = getNextLetterPackageFromSendingQueue();
        if (workingPackage != null && workingPackage.getLetter().getSendCount() <= RESEND_MAX) {
            executor.submit(new SdpLetterSenderService(workingPackage, serviceFacade));
        }
    }
}
catch (Exception e){
    serviceFacade.logActivity(null, null, ActivityLogActionType.APPLICATION, "Caught exception while polling for receipt.",getClass().getGenericSuperclass().toString(), getClass().getSimpleName(),e);
    logger.error("Caught exception while polling for receipt... Error: " + SdpServiceUtil.getStackTrace(e));
}

**Comment by runeflobakk** [comment]
Kan du sende stacktrace?

**Comment by bedzon** [comment]
Ok, dette er alt av stacktrace vi får:
2015-03-24 09:19:52,610 ERROR [SdpReceiptPollerService] no.krg.sdp.service.facade.threads.SdpReceiptPollerService - Caught exception while polling for receipt... Error: java.lang.ClassCastException: no.difi.begrep.sdp.schema_v10.SDPFeil cannot be cast to no.difi.begrep.sdp.schema_v10.SDPKvittering
        at no.digipost.api.representations.SimpleStandardBusinessDocument.getKvittering(SimpleStandardBusinessDocument.java:127)
        at no.digipost.api.representations.EbmsApplikasjonsKvittering.getKvittering(EbmsApplikasjonsKvittering.java:53)
        at no.krg.sdp.service.facade.threads.SdpReceiptPollerService.getLetterReceiptAndAcknowledgeLastOne(SdpReceiptPollerService.java:69)
        at no.krg.sdp.service.facade.threads.SdpReceiptPollerService.run(SdpReceiptPollerService.java:48)
        at java.lang.Thread.run(Thread.java:745)

**Comment by runeflobakk** [comment]
Dersom klassen deres `SdpReceiptPollerService` ikke bruker `SikkerDigitalPostKlient.hentKvittering(..)` eller `SikkerDigitalPostKlient.hentKvitteringOgBekreftForrige(..)`, så bør dere kalle `EbmsApplikasjonsKvittering.getStandardBusinessDocument()` for å få et `SimpleStandardBusinessDocument`. Denne klassen har følgende metoder for å sjekke hva slags type kvittering det er:

- `SimpleStandardBusinessDocument.erFeil()`
- `SimpleStandardBusinessDocument.erKvittering()`

Dette gjøres allerede her: https://github.com/difi/sikker-digital-post-java-klient/blob/master/src/main/java/no/difi/sdp/client/internal/KvitteringBuilder.java#L34-L56

Og dersom man bruker `SikkerDigitalPostKlient.hentKvittering(..)` eller `SikkerDigitalPostKlient.hentKvitteringOgBekreftForrige(..)`

**Comment by bedzon** [comment]
ok, ikke helt sikker på vad du mener med det siste du skriver.
Vi bruker den hentKvitteringOgBekreftForrige, det ser ut så her i kildekoden:
         ForretningsKvittering currentReceipt = getDigitalPostClient().hentKvitteringOgBekreftForrige(KvitteringForespoersel.builder(Prioritet.NORMAL).mpcId(mpcId).build(), lastReceipt);
Klarer den Forretningskvittering ikke å ta emot en feil?

**Comment by runeflobakk** [comment]
Iflg. stacktracen så gjør deres klasse `SdpReceiptPollerService.java` på linje 69 et kall til `EbmsApplikasjonsKvittering.getKvittering()`. Dette kallet må erstattes med et kall til EbmsApplikasjonsKvittering.getStandardBusinessDoc

**Comment by runeflobakk** [comment]
Iflg. stacktracen så gjør deres klasse SdpReceiptPollerService.java på linje 69 et kall til `EbmsApplikasjonsKvittering.getKvittering()`. Dette kallet må erstattes med et kall til `EbmsApplikasjonsKvittering.getStandardBusinessDocument()` for å få et `StandardBusinessDocument`

Hvis dere har en `ForretningsKvittering`:

```java
ForretningsKvittering fk = klient.hentKvitteringOgBekreftForrige(..);
StandardBusinessDocument sbd = fk.getStandardBusinessDocument();
if (sbd.erFeil()) {
   sbd.getFeil();
   // gjør ting med feilkvittering
} else if (sbd.erKvittering()) {
   sbd.getKvittering();
   // gjør ting med kvitteringen
}
```

Jeg ser at APIet her i klientbibliotekt ikke her helt bra m.t.p. [Law of Demeter](http://en.wikipedia.org/wiki/Law_of_Demeter), samt at metoden `EbmsApplikasjonsKvittering.getKvittering()` ikke burde vært der i det hele tatt. Jeg skal registrere et issue ang. deprecation og opprydning i dette.

**Comment by bedzon** [comment]
Bra, dere kan lukke denne saken nå. Takk for rask hjelp!

**Comment by runeflobakk** [comment]
Takk for rapport! :)
