### ISSUE TITLE
Truststore

### ISSUE THREAD

**Issue by idar** [difi/sikker-digital-post-java-klient#28]
Vi holder på å teste i produksjon: 
Der får vi følgende feil:
2015-03-30 12:06:02,266 [qtp904144151-21] INFO  mf.logger.translog - [sender] [984661185] UTGÅENDE PULLREQUEST mpc:[urn:norma
l:svarut] conversationId:[] instanceId:[] messageId:[44576edb-09c5-42dc-9479-fa692ccc1beb]  
2015-03-30 12:06:02,384 [qtp904144151-21] WARN  mf.logger.translog - [sender] [984661185] SOAPFAULT fault:[PolicyNoncomplianc
e]
2015-03-30 12:06:02,389 [qtp904144151-21] INFO  mf.logger.translog - [sender] [984661185] INNKOMMENDE EBMSFEIL mpc:[] convers
ationId:[] instanceId:[] messageId:[e9af2035-a48c-4070-9e33-aa564b79f0a5]  error:[PolicyNoncompliance][Error during certifica
te path validation: No trusted certs found; nested exception is org.apache.wss4j.common.ext.WSSecurityException: Error during
 certificate path validation: No trusted certs found]

I keystoren som privatekeyen ligger, ligger også de 4 sertifikatene fra http://begrep.difi.no/SikkerDigitalPost/1.2.0/sikkerhet/sertifikater/prod/

keytool -list
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 5 entries

cpnenterprisesha256class3, Mar 30, 2015, trustedCertEntry, 
Certificate fingerprint (SHA1): DC:38:AC:1C:B3:2A:5F:85:08:14:09:89:98:DA:D1:35:83:16:F4:86
bpclass3rootca, Mar 30, 2015, trustedCertEntry, 
Certificate fingerprint (SHA1): DA:FA:F7:FA:66:84:EC:06:8F:14:50:BD:C7:C2:81:A5:BC:A9:64:57
bpclass3ca3, Mar 30, 2015, trustedCertEntry, 
Certificate fingerprint (SHA1): D0:81:06:63:49:77:CA:EA:F2:16:45:BD:09:5D:CD:0D:E6:4C:F8:08
cpnrootcasha256class3, Mar 30, 2015, trustedCertEntry, 
Certificate fingerprint (SHA1): E7:47:8C:EA:79:5C:B6:AB:AA:1E:8B:AE:B5:08:A0:58:B4:8B:57:49
ks, Mar 25, 2015, PrivateKeyEntry, 
Certificate fingerprint (SHA1): A2:E9:C8:41:0A:D8:07:8E:70:E7:06:CD:E4:04:90:4B:24:75:32:61

**Comment by idar** [comment]
Bruker v 1.2.1

**Comment by landro** [comment]
@idar , jeg ser at meldingsformidleren gir dere en EBMS PolicyNoncompliance error. Hvem ønkser dere å sende på vegne av? Har dere fått opprettet en konto i mf og digipost? 
Er det noen grunn til at dere "tester" mot produksjon?

**Comment by aberner** [comment]
saken kan nok lukkes, da feilen kommer av at nødvendige tilganger ikke er gitt i produksjon enda.
